version: "3"

networks:
    backend:
        driver: bridge

services:
    redis:
        image: "bitnami/redis:latest"
        ports: 
            - "6379:6379"
        networks:
            - backend
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    
    mongo:
        image: "mongo:latest"
        networks:
            - backend
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=im_db
        volumes:
            - ./mongo_config/data:/data/db

    rest:
        image: "rest:latest"
        networks:
            - backend
        ports: 
            - "5000:5000"